### ISSUE TITLE
[General] mergify permissions

### ISSUE THREAD

**Issue by guillaumemichel** [libp2p/github-mgmt#251]
### Summary
We are facing [mergify issues](https://github.com/libp2p/rust-libp2p/pull/5604#issuecomment-2364651771) with branch protections webhooks with `rust-libp2p`, and @jxs has opened a ticket with Mergify support. Their answer was

>  Also, we sent an email around mid-july to grant additional permissions to the Mergify application, which are related to the branch protections webhooks, did you accept those ?

They said they cannot resend the link to accept the additional permissions to an external email

> We cannot send this email for just one organization. The following link should work for your libp2p org, but only organization admins can access it: https://github.com/organizations/libp2p/settings/installations/30827893/permissions/update

We are unable to view the link since we are not admin of the libp2p Github org.

### Why do you need this?

Fix Mergify on `rust-libp2p`

### What else do we need to know?

It would be perfect if an admin could approve the additional permissions (if reasonable), otherwise we could promote @jxs or myself temporarily so that we accept the permissions.

**DRI:** myself

**Comment by p-shahi** [comment]
@andyschwab are you able to see the link?

**Comment by andyschwab** [comment]
![Screenshot 2024-09-26 at 9 39 07 AM](https://github.com/user-attachments/assets/7e899ccb-236e-489a-ab72-7aa23073653f)

@aschmahmann, let me know if we're good to execute 👍

**Comment by andyschwab** [comment]
BuildPulse is also requesting additional permissions: 

![Screenshot 2024-09-26 at 9 41 59 AM](https://github.com/user-attachments/assets/f1a3069f-8d93-4498-a946-ddde456b0654)

**Comment by p-shahi** [comment]
@andyschwab please execute the mergify one.

**Comment by andyschwab** [comment]
Updated permissions have been accepted for Mergify. 

Mergify currently has access to a single repository: rust-libp2p

**Comment by p-shahi** [comment]
I'm closing this issue as done.
