### ISSUE TITLE
Optimizations in the json config

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/github-mgmt#6]
Instead of all the duplicate configs for each repo, is it possible to set a default config for all sibling keys?

e.g. looking at https://github.com/libp2p/github-mgmt/blob/77ee0e2b94ef068fdc6d969c62069020e18ba253/github/libp2p/team_repository.json#L3-L37, you can see that the Admin team has Admin permissions on all repos.. but instead of having to specify that explicitly for each repo, it would be nice if you could specify some default values and/or sugar syntax to map a set config to an array of repos.

**Comment by galargh** [comment]
Let's link it to this discussion about refactoring JSONs - https://github.com/protocol/github-mgmt-template/issues/36

**Comment by galargh** [comment]
I'll close this one and we'll track it in the issue I linked.
