### ISSUE TITLE
[General] Add ci check to ensure PR titles follows semantic release rules

### ISSUE THREAD

**Issue by mpetrunic** [libp2p/github-mgmt#81]
### Summary

Add github workflow to every js-libp2p* repo to check if PR title follows semantic release rules.
This action works great for us at chainsafe: https://github.com/amannn/action-semantic-pull-request

### Why do you need this?

To prevent accidentally merging community PR with invalid title which doesn't show in changelog.

### What else do we need to know?

**DRI:** myself

**Comment by galargh** [comment]
To accomplish this you could:
1. Create the `action-semantic-pull-request` file in https://github.com/libp2p/github-mgmt/tree/master/files/.github/workflows
1. Add a call which adds the workflow to all js repos to https://github.com/libp2p/github-mgmt/blob/master/scripts/src/actions/fix-yaml-config.ts. It'd have too look something like:
```js
addFileToAllRepos(
  '.github/workflows/action-semantic-pull-request.yml',
  '.github/workflows/action-semantic-pull-request.yml',
  (repository: Repository) => repository.name.startsWith('js-libp2p-')
)
```

**Comment by mxinden** [comment]
//CC @thomaseizinger given your work on https://github.com/libp2p/rust-libp2p/issues/3054.
